### ISSUE TITLE
Naming issue of `安装盘`

### ISSUE THREAD

**Issue by PAN-Ziyue** [ZJUSCT/mirror-front#12]
![截屏2022-03-14 下午9 22 30](https://user-images.githubusercontent.com/50222787/158180604-8176a6c1-06f0-4058-9ff0-26c082765626.png)

How about a more proper naming: `安装镜像`

**Comment by determ1ne** [comment]
参考 Debian 的网站对名称进行了更改（ https://github.com/ZJUSCT/mirror-front/commit/32deb8c68049a2fafc2c2b449964f3a5c26018af ）

中文：安装映像
英文：Installation Media
