### ISSUE TITLE
[UI/UX] Improve index page display

### ISSUE THREAD

**Issue by RalXYZ** [ZJUSCT/mirror-front#29]
# Background
Currently, we put all mirror cards in a big gird. This works properly when we do not have many cards, but will cause visual confusion to users if we have a lot of cards.  
In the current implementation ,although the card names is in lexicographic order, there does not exists a proper **tag** that shows the current position while user is scrolling. Take MS start menu as an example: 

![image](https://user-images.githubusercontent.com/19510622/178111735-519260d7-45e9-498c-9ff8-e0a388011086.png)

# Target
User needs to
- easily jump to the position he/she is looking for
- easily understand where they are (wile scrolling)

# Proposal
![image](https://user-images.githubusercontent.com/19510622/178111964-ba685956-2883-4c7b-a55c-bebcf946ddd8.png)  
This design is proposed by [rynco](https://github.com/lynzrand)

**Comment by wfwf1997** [comment]
Why not just introduce a search box? A user is more likely to find whether a certain mirror exists rather than use a distro only if they are presented.

**Comment by lynzrand** [comment]
> Why not just introduce a search box? A user is more likely to find whether a certain mirror exists rather than use a distro only if they are presented.

Fun fact: there _was_ a search box in the original design I proposed 😉

![图片](https://user-images.githubusercontent.com/10259119/178112238-bc012e14-2952-45c0-bfb1-309d40ea4b08.png)

**Comment by RalXYZ** [comment]
> Why not just introduce a search box? A user is more likely to find whether a certain mirror exists rather than use a distro only if they are presented.

Yes, we certainly needs a search box. It is necessary.  
Meanwhile, when I try to find a mirror, like `Ubuntu` on TUNA, I just scroll down and find `U`, then find `Ubuntu`, because my right hand is always on my mouse. To entering text, I need to move my right hand onto keyboard.  
So I think the enhancement in this proposal is *also* necessary.

**Comment by OrkWard** [comment]
Is this want you want? #68 
I've changed the fetch url in my develop environment so that it can be previewed on [github pages ](https://orkward.github.io/mirror-front)

**Comment by RalXYZ** [comment]
> Is this want you want? #68 I've changed the fetch url in my develop environment so that it can be previewed on [github pages ](https://orkward.github.io/mirror-front)

Absolutely. Thank you for your contribution. ♥
