### ISSUE TITLE
[UI/UX] Wrong theme color in header meta

### ISSUE THREAD

**Issue by wfwf1997** [ZJUSCT/mirror-front#30]
The theme color in the meta part of the header is not correct. For example, the primary color is `#157684` in the light mode. However, it becomes `#42a5f5` in the header part. Users using a compatible browser (e.g. Chrome mobile) will see a misfit header.

![Screenshot in Chrome mobile](https://user-images.githubusercontent.com/5110161/178113018-673043e3-c6f5-4765-991c-6fd9dbea57f6.png)

**Comment by iamNCJ** [comment]
fixed in 784b0a8
